version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-db:
    container_name: order-db
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"

  order-service:
    build: ./order
    image: order:latest
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/order_mongo.env

#  order-db:
#    image: redis:latest
#    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/stock_redis.env

#  stock-db:
#    image: redis:latest
#    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: payment:latest
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/payment_mongo.env

  payment-db:
    container_name: payment-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data_container:/data/db
