version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-db:
    container_name: order-db
    image: mongo
    command: mongod --port 27018
    logging:
      driver: "none"
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"

  order-service:
    build: ./order
    image: order:latest
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/order_mongo.env

#  order-db:
#    image: redis:latesta
#    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/stock_redis.env

  stock-db:
    image: redis:latest
    logging:
      driver: "none"
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service0:
    build: ./payment
    image: payment:latest
    expose:
      - "5000"
    command: gunicorn --worker-class=gevent --worker-connections=1000 -b 0.0.0.0:5000 app:app # -k gevent --worker-connections 100 (i dont know why this not working) could also add --threads 12
    environment:
      - OTHER_NODE=http://payment-service1
      - PORT=27017
      - GATEWAY_URL=mongodb://payment-db0:27017/db
      - REPLICATION_NUMBER=0
      - FLASK_ENV=development

  payment-service1:
    build: ./payment
    image: payment:latest
    expose:
      - "5000"
    command: gunicorn --worker-class=gevent --worker-connections=1000 -b 0.0.0.0:5000 app:app
#    env_file:
#      - env/payment_mongo.env
    environment:
      - OTHER_NODE=http://payment-service0
      - PORT=27019
      - GATEWAY_URL=mongodb://payment-db1:27019/db
      - REPLICATION_NUMBER=1
      - FLASK_ENV=development


  coordinator-service:
    build: ./coordinator
    image: coordinator:latest
    command: gunicorn -b 0.0.0.0:5000 app:app

  payment-db0:
    container_name: payment-db0
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data_container:/data/db

  payment-db1:
    container_name: payment-db1
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27019:27019"
    command: mongod --port 27019
    volumes:
      - ./mongodb_data_container:/data/db1
