apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    component: order
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-set
spec:
  replicas: 1
  serviceName: order-service
  selector:
    matchLabels:
      component: order
  template:
    metadata:
      labels:
        component: order
    spec:
      containers:
        - name: order
          image: zegermouw/order:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: PAYMENT_SERVICE_URL
              value: "payment-service"
            - name: STOCK_SERVICE_URL
              value: "stock-service"
            - name: ORDER_GATEWAY
              value: "mongodb://localhost:27018/db"
            - name: ORDER_PORT
              value: "27018"
        - name: order-db
          args:
            - mongod
            - --port
            - "27018"
          image: mongo
          ports:
            - containerPort: 27018
          volumeMounts:
            - mountPath: /data/db
              name: order-pvc
  volumeClaimTemplates:
    - metadata:
        name: order-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi


