apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    component: payment
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment
  template:
    metadata:
      labels:
        component: payment
    spec:
      containers:
        - name: payment
          image: payment:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: GATEWAY_URL
              value: mongodb://payment-db:27017/db
            - name: PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    component: payment-db
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: payment-db
    spec:
      containers:
        - image: mongo
          name: payment-db
          ports:
            - containerPort: 27017
