
apiVersion: v1
kind: Service
metadata:
  name: stock-updater-service
spec:
  type: LoadBalancer
  selector:
    component: stock-updater
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-updater-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stock-updater
  template:
    metadata:
      labels:
        component: stock-updater
    spec:
      containers:
        - name: stock-updater
          image: markodorko/stock-updater:latest 
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app", --threads 2]